"""Update OutboxMixin

Revision ID: 63aaf9466475
Revises: 3d46f7ffc204
Create Date: 2025-12-20 12:25:59.836065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63aaf9466475'
down_revision: Union[str, Sequence[str], None] = '3d46f7ffc204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_outbox_events', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('auth_outbox_events', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('auth_outbox_events', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('auth_outbox_events', sa.Column('last_error', sa.String(), nullable=True))
    op.create_index(op.f('ix_auth_outbox_events_scheduled_at'), 'auth_outbox_events', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_auth_outbox_events_status'), 'auth_outbox_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_outbox_events_status'), table_name='auth_outbox_events')
    op.drop_index(op.f('ix_auth_outbox_events_scheduled_at'), table_name='auth_outbox_events')
    op.drop_column('auth_outbox_events', 'last_error')
    op.drop_column('auth_outbox_events', 'scheduled_at')
    op.drop_column('auth_outbox_events', 'attempts')
    op.drop_column('auth_outbox_events', 'status')
    # ### end Alembic commands ###
