"""Add Users tables

Revision ID: dbb059ab58ed
Revises: 63aaf9466475
Create Date: 2026-01-09 21:02:33.687046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbb059ab58ed'
down_revision: Union[str, Sequence[str], None] = '63aaf9466475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('users_outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_outbox_events_processed_at'), 'users_outbox_events', ['processed_at'], unique=False)
    op.create_index(op.f('ix_users_outbox_events_scheduled_at'), 'users_outbox_events', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_users_outbox_events_status'), 'users_outbox_events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_outbox_events_status'), table_name='users_outbox_events')
    op.drop_index(op.f('ix_users_outbox_events_scheduled_at'), table_name='users_outbox_events')
    op.drop_index(op.f('ix_users_outbox_events_processed_at'), table_name='users_outbox_events')
    op.drop_table('users_outbox_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
